<#
    Converts a full-week report (fetched from a currentscores?id= URL and
    saved to a text file - see README "Importing a full-week report") into a
    scripts\lineup-sources\<date>.ps1 data file, ready for
    Import-WeekReport.ps1.

    Expects the report text in the form:
        ## Matchup N: TeamA (Win/Loss) vs TeamB (Win/Loss)
        **TeamA:**
        - Bowler Name (Regular|Blind|Substitute, Avg NNN): g1, g2, g3 = total
        ...
        **TeamB:**
        ...
    (one bowler line per roster position, in seat order - this is the actual
    ground truth for head-to-head pairing.)

    Usage:
        .\scripts\Parse-WeekReport.ps1 -InputFile week1_report.txt -Date 2026-08-18 `
            -OutFile scripts\lineup-sources\2026-08-18.ps1

    Always review the generated file before running Import-WeekReport.ps1 -
    this is a best-effort transcription, not a substitute for the sanity
    checks Import-WeekReport.ps1 runs at import time.
#>
param(
    [Parameter(Mandatory)] [string]$InputFile,
    [Parameter(Mandatory)] [string]$Date,
    [Parameter(Mandatory)] [string]$OutFile
)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$text = Get-Content -Raw $InputFile

# ---- current team -> official regular-bowler names (for best-effort subFor) ----
$snapshotRoot = Join-Path $root 'data\raw'
$latestSnap = Get-ChildItem $snapshotRoot -Directory | Sort-Object Name -Descending | Select-Object -First 1
$teamRegularNames = @{}
if ($latestSnap) {
    $standingsPath = Join-Path $latestSnap.FullName 'standings.json'
    if (Test-Path $standingsPath) {
        $standings = (Get-Content -Raw $standingsPath | ConvertFrom-Json).data
        $idToName = @{}
        Get-ChildItem $latestSnap.FullName -Filter 'team_*.json' | ForEach-Object {
            $teamData = (Get-Content -Raw $_.FullName | ConvertFrom-Json).data
            foreach ($b in $teamData) { $idToName[$b._id] = $b.name }
        }
        foreach ($row in $standings.standings) {
            if (-not $row.team._id) { continue }
            $names = @($row.bowlerInfos | ForEach-Object { $idToName[$_._id] } | Where-Object { $_ })
            $teamRegularNames[$row.team.name] = $names
        }
    }
}

# ---- parse team blocks ----
$blockRx = [regex]'(?m)^\*\*(?<team>[^\r\n]+?):\*\*\r?\n(?<body>(?:-[^\r\n]*\r?\n?)+)'
$lineRx  = [regex]'^-\s*(?<name>.+?)\s*\((?<kind>Regular|Blind|Substitute),\s*Avg\s*(?<avg>\d+)\)\s*:'

$teams = [ordered]@{}
foreach ($m in $blockRx.Matches($text)) {
    $tname = $m.Groups['team'].Value.Trim()
    $bowlerLines = @($m.Groups['body'].Value -split "`n" | Where-Object { $lineRx.IsMatch($_) })
    if ($bowlerLines.Count -eq 0) { continue }   # not a real team block (e.g. matched something else)

    $entries = @()
    foreach ($ln in $bowlerLines) {
        $lm = $lineRx.Match($ln)
        $name = $lm.Groups['name'].Value.Trim()
        $kind = $lm.Groups['kind'].Value
        $avg  = [int]$lm.Groups['avg'].Value
        if ($kind -eq 'Substitute' -and $name -eq 'Vacant') {
            $entries += [ordered]@{ name = 'Vacant'; kind = 'blind'; avg = $avg; subFor = $null; blindFor = $null }
        } elseif ($kind -eq 'Blind') {
            $entries += [ordered]@{ name = $name; kind = 'blind'; avg = $avg; subFor = $null; blindFor = $name }
        } elseif ($kind -eq 'Substitute') {
            $entries += [ordered]@{ name = $name; kind = 'sub'; avg = $avg; subFor = $null; blindFor = $null }
        } else {
            $entries += [ordered]@{ name = $name; kind = 'bowler'; avg = $avg; subFor = $null; blindFor = $null }
        }
    }

    # best-effort subFor: only when exactly 1 regular is missing and exactly 1 sub present
    $present = @($entries | Where-Object { $_.kind -ne 'sub' } | ForEach-Object { $_.name })
    $official = @($teamRegularNames[$tname])
    $missing = @($official | Where-Object { $present -notcontains $_ })
    $subs = @($entries | Where-Object { $_.kind -eq 'sub' })
    if ($missing.Count -eq 1 -and $subs.Count -eq 1) {
        ($entries | Where-Object { $_.kind -eq 'sub' } | Select-Object -First 1).subFor = $missing[0]
    }

    $teams[$tname] = $entries
}

# ---- emit the data file ----
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("# Auto-generated by Parse-WeekReport.ps1 from $InputFile - REVIEW BEFORE IMPORTING.")
[void]$sb.AppendLine('$teams = [ordered]@{')
foreach ($tname in $teams.Keys) {
    $tq = $tname.Replace("'", "''")
    [void]$sb.AppendLine("    '$tq' = @(")
    foreach ($e in $teams[$tname]) {
        $nq = "$($e.name)".Replace("'", "''")
        $parts = @("T '$nq' $($e.avg)")
        if ($e.kind -ne 'bowler') { $parts += "'$($e.kind)'" }
        if ($e.kind -eq 'sub')   { $parts += $(if ($e.subFor) { "'$($e.subFor.Replace("'", "''"))'" } else { '$null' }) }
        if ($e.kind -eq 'blind') { $parts += '$null'; $parts += $(if ($e.blindFor) { "'$($e.blindFor.Replace("'", "''"))'" } else { '$null' }) }
        [void]$sb.AppendLine("        $($parts -join ' ')")
    }
    [void]$sb.AppendLine('    )')
}
[void]$sb.AppendLine('}')
$sb.ToString() | Set-Content -Encoding utf8 $OutFile
Write-Host "Parsed $($teams.Count) teams -> $OutFile (review before importing)"
