# Auto-generated by Parse-WeekReport.ps1 from C:\Users\Adam\AppData\Local\Temp\claude\C--Users-Adam-Downloads\2df331c9-7c47-4e6c-b78b-a3623fc8cde9\scratchpad\week6_report.txt - REVIEW BEFORE IMPORTING.
$teams = [ordered]@{
    'SHARKS' = @(
        T 'Matt Padilla' 209
        T 'David Padilla' 191
        T 'Vincent Padilla' 195
        T 'Todd Sanders' 219
        T 'Mark Hoffman' 238
    )
    'Busting Nuts' = @(
        T 'Audra Tafoya' 176
        T 'Dan Mehman' 151
        T 'Mike Read' 177
        T 'Dustin Richardson' 178
        T 'Kole Silz' 189
    )
    'No Llores' = @(
        T 'Chris Imel' 204
        T 'Justin Gonzales' 195
        T 'Jesus Meraz' 189
        T 'Robb Vigil' 194
        T 'Eric Cummings' 228
    )
    'Wheelhouse' = @(
        T 'Wayne Gosselin' 159
        T 'Thomas Holt' 173
        T 'Mick Coakley' 191
        T 'Phillip Gosselin' 194
        T 'Ryan Holt' 207
    )
    'Apex Auto Glass' = @(
        T 'Tham Namvong' 207
        T 'Jerry Navasack' 157
        T 'Bounethai Novankham' 196
        T 'Somdeth Sinouansai' 226
        T 'John Gwynn' 247
    )
    'THE DEN' = @( # renamed from "Sweetman Racing" this same week - Build-Stats.ps1 keys lineup files by CURRENT team name
        T 'Van Vasquez' 164
        T 'Rich Lista' 197
        T 'Kevin Sweetman' 193
        T 'James Eisenhauer' 177
        T 'Alex Gott' 205
    )
    'Crippled Khaos' = @(
        T 'Mark Donner' 174
        T 'Gregory Fistell' 208
        T 'Stephanie David' 183
        T 'William Kondrotis' 198
        T 'Stephen Sutton' 211
    )
    'Multiple Scorgasms' = @(
        T 'Phoenix Chavez' 216
        T 'Bobby Torrez' 187
        T 'Frank Ramirez' 184
        T 'Jermaine Mccarter' 187
        T 'Mike Chavez' 202
    )
    'Luxury Box Sports' = @(
        T 'Jamaal Calhoun' 213
        T 'Aaron Chilton' 204
        T 'Rayvone Hackshaw' 203
        T 'Jeffrey Jones' 211
        T 'Benjie Garrison' 228
    )
    'Mike Litzwet' = @(
        T 'Zach Joslin' 213
        T 'John Schissler' 194
        T 'Derek Schissler' 204
        T 'Frank Guccione' 209
        T 'Ricky Schissler' 228
    )
    'LET''S GET IT!' = @(
        T 'Jermaine Brown' 216
        T 'Howard Moore' 206
        T 'Sharon Coleman' 180
        T 'Rick Armstrong (Showtime)' 202
        T 'Ishmael Smittie' 205
    )
    'Rocky Mountain Tap & Garden' = @(
        T 'Doug Mclaughlin' 196
        T 'Chris Landis' 205
        T 'Linda Conklin' 149
        T 'Terry Conklin' 197
        T 'Max Landis' 204
    )
    'Motiv' = @(
        T 'Katrina Suthers' 196
        T 'Julian Torres' 204
        T 'Steven Armijo' 188
        T 'Kenny Robinson' 208 'sub' $null
        T 'Johnny Camacho' 211
    )
    'Hot XXX' = @(
        T 'Brian Farrell' 187
        T 'Garrett Hatch' 201
        T 'Cameron Alcorn' 185
        T 'Tony Silva' 227
        T 'Mark Umscheid' 236
    )
    'Throw A Better Ball' = @(
        T 'Andrew Schlehuber' 199
        T 'Adam Salinas' 208
        T 'William A Gotwald' 198
        T 'Damion Rangel' 212
        T 'Mario Vigil' 214
    )
    'Buzz Roofing' = @(
        T 'Brett Elliott' 215
        T 'Ryan Modica' 210
        T 'Galen Sisto' 185
        T 'Keith Kondratko' 207
        T 'Frank Busnardo' 203
    )
    'Bowlscore.com' = @(
        T 'Ted Vargas' 190
        T 'Rodwyn Lyons Sr' 196
        T 'Lee Schwartz' 213
        T 'Ed Cutshaw' 216
        T 'Adam Philp' 225
    )
    'StarDust Lounge' = @(
        T 'Rene Movilion' 184
        T 'Cristina Gunnett' 193
        T 'Bob Burkhead' 205
        T 'Ian Pike' 219
        T 'Greg Davies Jr' 229
    )
    'Leave Your Mark Pro Shop' = @(
        T 'Marco Popovich' 221
        T 'Brenna Tripp' 198
        T 'Hailey Howard' 218
        T 'Aaron Howard' 212
        T 'Timothy Tripp' 230
    )
    'Aftermath' = @(
        T 'Nick Sandoval' 198
        T 'Jennifer Davis' 199
        T 'Eddie Lara' 203
        T 'Dion Griego' 202
        T 'Duane Martinac' 237
    )
    'PIN-A-TRATORS' = @(
        T 'Benjamin Morgan' 233
        T 'Greg Hydle' 207
        T 'David Owens' 191
        T 'Greg Morgan' 231
        T 'Deon Fleming' 228
    )
    'Matrix Auto Body' = @(
        T 'Scott Bruce' 204
        T 'Richard Isaacs' 190
        T 'Dave Simpson' 201
        T 'Brandon May' 198
        T 'Larry May' 210
    )
    'The Money Team' = @(
        T 'Bobby Hurtado' 199
        T 'Matthew Quintana' 176
        T 'Devon Hilliard' 188
        T 'Joseph Guinn' 204
        T 'Blair Watkins' 196
    )
    'Last Minute' = @(
        T 'Erick Podwill' 205
        T 'Gabby Pineda' 200
        T 'Fred Pedroza' 190
        T 'Shawn Clements' 206
        T 'Dru Martin' 220
    )
    'J. Crew' = @(
        T 'Pierre Lopez' 168
        T 'Paul Schleigh' 199
        T 'Craig Stout' 203
        T 'Robert Gift' 202
        T 'Lee Ripley' 217
    )
    'Over the Line' = @(
        T 'Kelly Lawson' 189
        T 'Shawn Claussen' 205
        T 'Rey Rodriguez' 189
        T 'Anthony Aragon' 212
        T 'Noah Werner' 231
    )
    'Mother Chuckers' = @(
        T 'Erin Marchant' 202
        T 'Trey Erickson' 202
        T 'Chuck Dreux' 199
        T 'Tim Pester' 218
        T 'Bryan Keller' 216
    )
    'Better Than Gold' = @(
        T 'Eric Phillips' 231
        T 'Chad Schneider' 189
        T 'Taryn Frenzel' 199
        T 'Craig Moravy' 213
        T 'Lee Kastberg' 212
    )
    'SASQUATCHED' = @(
        T 'Frank Torrez' 196
        T 'Blaize Walker' 221
        T 'Chris Naab' 207
        T 'Anthony Unrein IV' 200
        T 'Greg Wobbema' 211
    )
    'Sloppy Hookers' = @(
        T 'Rich Pennal' 187
        T 'John Crowder' 166
        T 'Robert McQuoid' 193
        T 'Adam Perski' 218
        T 'Trey Simpson' 199
    )
    'The Bowler Depot' = @(
        T 'Anthony Allen' 222
        T 'Jo Struble' 214
        T 'Roger Wahler' 212
        T 'Adam D Sakowski' 226
        T 'Cody Vaughn' 241
    )
    'Lamorie Painting' = @(
        T 'Rudy Lamorie' 214
        T 'Gary Losh' 211
        T 'Justin Phillips' 213
        T 'Nicholas Peterson-Pedroza (Nick Pedroza)' 210
        T 'Eric Hernlund' 226
    )
    'Chicken Nuggies' = @(
        T 'William Reynolds' 209
        T 'Sarah Garofano' 163
        T 'Justyne Jansen' 208
        T 'Brian Douglass' 211
        T 'Dante Lundy' 245
    )
    'Rocky Mountain High' = @(
        T 'Bob Johnson' 156
        T 'Scott Carothers' 223
        T 'Mike Vasquez' 199
        T 'Nolan Carothers' 180
        T 'Mike Hinsley' 217
    )
    'Pocket Aces' = @(
        T 'Aj Woodvine' 208
        T 'Greg Baldassar' 195
        T 'Brian Moss' 211
        T 'Jason Busnardo' 226
        T 'Roman Archuleta' 223
    )
    'Corpse Crew' = @(
        T 'Joe Panetta' 80
        T 'Tanya Craig' 161
        T 'Randy Cleghorn' 196
        T 'Kayla Osei' 185
        T 'Josh Henshaw' 197
    )
    'Panetta Heating' = @(
        T 'Rocco Panetta' 192
        T 'Jeffrie Delaney' 227
        T 'Tony Panetta' 174
        T 'Robert Gieck' 222
        T 'Randy Wood' 242
    )
    'Denver Vibrator' = @(
        T 'Jami May-Bruce' 190
        T 'Ron Burley' 221
        T 'Ron Wooley' 202
        T 'Austin Huyser' 215
        T 'Jeff Lagrange' 211
    )
    'Kamikaze Keglers' = @(
        T 'Zach Knight (Zachary Knight)' 185
        T 'JJ Harnke' 189
        T 'Brian Garramone' 213
        T 'Jon Hanson' 197
        T 'Spenser Hanson' 223
    )
    'Light ''Em Up' = @(
        T 'Wes Widick' 197
        T 'Brian Birely' 205
        T 'Shaun Labay' 204
        T 'Derek Birely' 237
        T 'Jared Birely' 235
    )
}

