# Auto-generated by Parse-WeekReport.ps1 from C:\Users\Adam\AppData\Local\Temp\claude\C--Users-Adam-Downloads\2df331c9-7c47-4e6c-b78b-a3623fc8cde9\scratchpad\week3_report.txt - REVIEW BEFORE IMPORTING.
$teams = [ordered]@{
    'Luxury Box Sports' = @(
        T 'Jamaal Calhoun' 213
        T 'Aaron Chilton' 214
        T 'Rayvone Hackshaw' 205
        T 'Jeffrey Jones' 214
        T 'Benjie Garrison' 223
    )
    'Sweetman Racing' = @(
        T 'Van Vasquez' 174
        T 'Rich Lista' 197
        T 'Kevin Sweetman' 193
        T 'James Eisenhauer' 187
        T 'Alex Gott' 197
    )
    'LET''S GET IT!' = @(
        T 'Robert Coleman' 182
        T 'Howard Moore' 194
        T 'Jermaine Brown' 204
        T 'Rick Armstrong (Showtime)' 204
        T 'Ishmael Smittie' 197
    )
    'Multiple Scorgasms' = @(
        T 'Phoenix Chavez' 215
        T 'Bobby Torrez' 194
        T 'Frank Ramirez' 182
        T 'Antonio Garcia' 204 'blind' $null 'Antonio Garcia'
        T 'Mike Chavez' 208
    )
    'Rocky Mountain Tap & Garden' = @(
        T 'Becky Gee' 153
        T 'Linda Conklin' 149
        T 'Courtney Hayes' 191
        T 'Troy Wilson' 195
        T 'Terry Conklin' 201
    )
    'Schissler''s Army' = @(
        T 'Zach Joslin' 202
        T 'John Schissler' 191
        T 'Aaron Schissler' 203
        T 'Derek Schissler' 210
        T 'Ricky Schissler' 222
    )
    'Motiv' = @(
        T 'Katrina Suthers' 193
        T 'Julian Torres' 196
        T 'Nick Fritchell' 206
        T 'Nicholas B Todack' 211
        T 'Johnny Camacho' 215
    )
    'Throw A Better Ball' = @(
        T 'Damion Rangel' 199
        T 'Mariah Salinas' 154
        T 'Adam Salinas' 196
        T 'Andrew Schlehuber' 207
        T 'Mario Vigil' 213
    )
    'Bowlscore.com' = @(
        T 'Ted Vargas' 200
        T 'Rodwyn Lyons Sr' 206
        T 'Lee Schwartz' 211
        T 'Ed Cutshaw' 212
        T 'Guy Blunt' 221
    )
    'Hot XXX' = @(
        T 'Brian Farrell' 168
        T 'Aaron Levine' 198
        T 'Cameron Alcorn' 178
        T 'Timothy Lehl' 212
        T 'Mark Umscheid' 226
    )
    'Leave Your Mark Pro Shop' = @(
        T 'Marco Popovich' 226
        T 'Brenna Tripp' 208
        T 'Hailey Howard' 202
        T 'Aaron Howard' 221
        T 'Timothy Tripp' 231
    )
    'Buzz Roofing' = @(
        T 'Brett Elliott' 205
        T 'Galen Sisto' 193
        T 'Lu Busnardo' 189
        T 'Keith Kondratko' 207
        T 'Frank Busnardo' 213
    )
    'PIN-A-TRATORS' = @(
        T 'Benjamin Morgan' 222
        T 'Jayden Cary' 205
        T 'David Owens' 201
        T 'Greg Morgan' 223
        T 'Deon Fleming' 225
    )
    'StarDust Lounge' = @(
        T 'John Lund' 206
        T 'Rene Movilion' 184
        T 'Bob Burkhead' 207
        T 'Ian Pike' 220
        T 'Greg Davies Jr' 222
    )
    'The Money Team' = @(
        T 'John Laws' 211
        T 'Bobby Hurtado' 199
        T 'Nicole Demonte' 124
        T 'Matthew Quintana' 172
        T 'Joseph Guinn' 206
    )
    'Aftermath' = @(
        T 'Nick Sandoval' 201
        T 'Jennifer Davis' 198
        T 'Eddie Lara' 203
        T 'Dion Griego' 206
        T 'Geno Lavigna' 215
    )
    'J. Crew' = @(
        T 'Craig Stout' 207
        T 'Pierre Lopez' 177
        T 'Robert Gift' 210
        T 'Lee Ripley' 217
        T 'Michael Ligeski' 221
    )
    'Matrix Auto Body' = @(
        T 'Scott Bruce' 204
        T 'Richard Isaacs' 196
        T 'Dave Simpson' 205
        T 'Brandon May' 201
        T 'Larry May' 212
    )
    'Mother Chuckers' = @(
        T 'Erin Marchant' 203
        T 'Trey Erickson' 190
        T 'Chuck Dreux' 193
        T 'Tim Pester' 220
        T 'Bryan Keller' 214
    )
    'Last Minute' = @(
        T 'Erick Podwill' 213
        T 'Laszlo Soos' 197
        T 'Shawn Clements' 206
        T 'Fred Pedroza' 200
        T 'Dru Martin' 205
    )
    'SASQUATCHED' = @(
        T 'Greg Wobbema' 217
        T 'Blaize Walker' 207
        T 'Chris Naab' 202
        T 'Anthony Unrein IV' 210
        T 'Sam Johns' 203
    )
    'Over the Line' = @(
        T 'Kelly Lawson' 199
        T 'Shawn Claussen' 215
        T 'Rey Rodriguez' 189
        T 'Noah Werner' 218
        T 'Jon Brockett' 211
    )
    'The Bowler Depot' = @(
        T 'Anthony Allen' 206
        T 'Jo Struble' 210
        T 'Adam D Sakowski' 217
        T 'Roger Wahler' 209
        T 'Cody Vaughn' 223
    )
    'Better Than Gold' = @(
        T 'Eric Phillips' 212
        T 'Chad Schneider' 189
        T 'Taryn Frenzel' 204
        T 'Craig Moravy' 212
        T 'Lee Kastberg' 218
    )
    'Chicken Nuggies' = @(
        T 'William Reynolds' 209
        T 'Sarah Garofano' 173
        T 'Justyne Jansen' 202
        T 'Brian Douglass' 220
        T 'Dante Lundy' 239
    )
    'Sloppy Hookers' = @(
        T 'Rich Pennal' 187
        T 'John Crowder' 166
        T 'Robert McQuoid' 203
        T 'Adam Perski' 218
        T 'Trey Simpson' 199
    )
    'Pocket Aces' = @(
        T 'Aj Woodvine' 217
        T 'Greg Baldassar' 205
        T 'Brian Moss' 211
        T 'Jason Busnardo' 223
        T 'Roman Archuleta' 233
    )
    'Lamorie Painting' = @(
        T 'Rudy Lamorie' 205
        T 'Gary Losh' 190
        T 'Justin Phillips' 208
        T 'Nicholas Peterson-Pedroza (Nick Pedroza)' 210
        T 'Eric Hernlund' 217
    )
    'Panetta Heating' = @(
        T 'Rocco Panetta' 202
        T 'Jeffrie Delaney' 223
        T 'Tony Panetta' 163
        T 'Gianna E Panetta' 195
        T 'Randy Wood' 238
    )
    'Rocky Mountain High' = @(
        T 'Bob Johnson' 166
        T 'Scott Carothers' 208
        T 'Mike Vasquez' 188
        T 'Nolan Carothers' 176
        T 'Mike Hinsley' 216
    )
    'Kamikaze Keglers' = @(
        T 'Zach Knight (Zachary Knight)' 185
        T 'JJ Harnke' 187
        T 'Spenser Hanson' 204
        T 'Dave Eddy' 212
        T 'Brian Garramone' 218
    )
    'Corpse Crew' = @(
        T 'Kayla Osei' 185
        T 'Randy Cleghorn' 189
        T 'Joe Panetta' 82
        T 'Tanya Craig' 171
        T 'Josh Henshaw' 197 'blind' $null 'Josh Henshaw'
    )
    'SHARKS' = @(
        T 'Todd Sanders' 212 'blind' $null 'Todd Sanders'
        T 'Matt Padilla' 219
        T 'David Padilla' 201
        T 'Vincent Padilla' 195
        T 'Mark Hoffman' 218
    )
    'Denver Vibrator' = @(
        T 'Jami May-Bruce' 194
        T 'Austin Huyser' 202
        T 'Ron Wooley' 203
        T 'Jeff Lagrange' 208
        T 'Ron Burley' 221
    )
    'No Llores' = @(
        T 'Chris Imel' 204
        T 'Derek Gonzales' 203
        T 'Jesus Meraz' 199
        T 'Robb Vigil' 199
        T 'Eric Cummings' 216
    )
    'Light ''Em Up' = @(
        T 'Shaun Labay' 204
        T 'Brian Birely' 202
        T 'Wes Widick' 199
        T 'Derek Birely' 221
        T 'Jared Birely' 233
    )
    'Apex Auto Glass' = @(
        T 'Tham Namvong' 217
        T 'Jerry Navasack' 157
        T 'Bounethai Novankham' 198
        T 'Somdeth Sinouansai' 214
        T 'John Gwynn' 237
    )
    'Busting Nuts' = @(
        T 'Audra Tafoya' 166
        T 'Dan Mehman' 141
        T 'Mike Read' 178
        T 'Dustin Richardson' 183
        T 'Kole Silz' 155
    )
    'Crippled Khaos' = @(
        T 'Mark Donner' 184
        T 'Gregory Fistell' 202
        T 'Stephanie David' 193
        T 'William Kondrotis' 207
        T 'Stephen Sutton' 211 'blind' $null 'Stephen Sutton'
    )
    'Wheelhouse' = @(
        T 'Wayne Gosselin' 153
        T 'Mick Coakley' 179
        T 'Stefan Holt' 200
        T 'Phillip Gosselin' 204
        T 'Ryan Holt' 205
    )
}

